name: Verify Peribolos
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  project:
    name: Verify peribolos
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: src/github.com/emporous/.github
      - name: verify go modules and vendor directory
        run: |
          go mod tidy
          go mod vendor
        working-directory: src/github.com/emporous/.github
      - name: running unit tests
        run: |
          go test ./... --config ../peribolos.yaml --owners-dir ../
        working-directory: src/github.com/emporous/.github
